image: java:8-jdk

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test
  - pages

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  script:
   - ./gradlew test
   - ./gradlew javadoc
   - ./gradlew jacocoTestReport
  artifacts:
    paths:
    - build/reports/jacoco/test/html/

pages:
  script:
   - ./gradlew javadoc
   - mkdir public
   - cp -r build/docs/javadoc public
  artifacts:
    paths:
    - public
  only:
   - master

